version: "3.8"

services:
  drupal:
    build: ./varbase-conf
    restart: always
    networks:
      - external
      - internal
    volumes:
      - ./drupal/modules:/var/www/html/modules
      - ./drupal/profiles:/var/www/html/profiles
      - ./drupal/sites:/var/www/html/sites
      - ./drupal/themes:/var/www/html/themes
      - drupal-site:/var/www/html/
    env_file:
      - db.env
    depends_on:
      - database

  database:
    image: mariadb:10.5.6-focal
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - internal
    volumes:
      - site-database:/var/lib/mysql
    env_file:
      - db.env

  web-server:
    image: nginx:1.19.3-alpine
    restart: always
    networks:
      - external
    ports:
      - 8080:80
    volumes:
      - drupal-site:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - drupal

networks:
  external:
  internal:

volumes:
  drupal-site:
  site-database:
