version: "3.8"

services:
  drupal:
    build: ./varbase-conf
    restart: always
    networks:
      - external
      - internal
    volumes:
      - ./drupal:/var/www/html
    env_file:
      - db.env
    depends_on:
      - database

  database:
    image: mariadb:10.5.6-focal
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - internal
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./mariadb-startup-scripts:/docker-entrypoint-initdb.d
    env_file:
      - db.env

  web-server:
    image: nginx:1.19.3-alpine
    restart: always
    networks:
      - external
    ports:
      - 8080:80
    volumes:
      - ./drupal:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - drupal

networks:
  external:
  internal:

volumes:
  drupal-site:
